### ISSUE TITLE
Forward Dp approach could also be added to CountTheNumberOfWaysToReachAScoreI

### ISSUE THREAD

**Issue by RohitJain3241** [suresh-gandhi/DP#1]
We could start from 0 uptil N and update all the possible states from where we are. 
For Ex:- When we are on 0 we update 1, 3 and 5  Or when we are on 1 we could update 2, 4, 6 and so on...

**Comment by suresh-gandhi** [comment]
Surely we can do that @RohitJain3241 . I just thought since it is not cutting the input(score) by significant factors(like score/2, score/5 etc) and doing it linearly(score - 2, score - 5), so recursion with memoization(sometimes more intuitive to me and easy to write :P) would be better.

**Comment by suresh-gandhi** [comment]
And why are we talking here in english btw :P

**Comment by RohitJain3241** [comment]
Complexity wise recursive approach/memoization is better. But, to accumulate all the results in 1 file and then compare would be better for revision. :)

**Comment by suresh-gandhi** [comment]
yeah u r correct. I think i should add it to my solution.

**Comment by RohitJain3241** [comment]
Now you can close this issue. @summigandhi
